### ISSUE TITLE
Restart Button

### ISSUE THREAD

**Issue by ilovemariobro** [Web4L/Minesweeper#5]
Commonly, I've seen some minesweeper games use a keybind or a button on the screen that allows for the player to restart their game. For example, you could bind R to restart, and then whenever the player presses R, the game resets. 

I suggest that a system like this be implemented into the game. This allows the player to restart their game whenever they want, and they do not have to wait for the end.

**Comment by dani3ljh** [comment]
This has been added in "Fixed Button Placement" commit
